<a href="https://colab.research.google.com/github/uppupushpa/practice/blob/main/Data_Cleaning_and_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Example of Messy Data
data={
    "Name": ["Pushpa","bhavya","varshini","sathvika",None,"abhi"],
    "Age": [22,28, np.nan,21,30,25],
    "City": ["Hyd","Delhi","hyd","delhi","Delhi","Hyd"]
}

df=pd.DataFrame(data)
df

       Name   Age   City
0    Pushpa  22.0    Hyd
1    bhavya  28.0  Delhi
2  varshini   NaN    hyd
3  sathvika  21.0  delhi
4      None  30.0  Delhi
5      abhi  25.0    Hyd

In [3]:
# First few rows
print(df.head())
print('this is info()====================')

# Data info
print(df.info())
print('this is describe()====================')
# Summary statistics
print(df.describe())

       Name   Age   City
0    Pushpa  22.0    Hyd
1    bhavya  28.0  Delhi
2  varshini   NaN    hyd
3  sathvika  21.0  delhi
4      None  30.0  Delhi
this is info()====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      float64
 2   City    6 non-null      object
dtypes: float64(1), object(2)
memory usage: 276.0+ bytes
None
this is describe()====================
             Age
count   5.000000
mean   25.200000
std     3.834058
min    21.000000
25%    22.000000
50%    25.000000
75%    28.000000
max    30.000000

In [4]:
# Check missing values
print(df.isnull())

# Count missing values
df.isnull().sum() #count of missing values

    Name    Age   City
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False  False
4   True  False  False
5  False  False  False

Name    1
Age     1
City    0
dtype: int64

In [5]:
# Drop rows with missing values
df_drop = df.dropna()
df_drop

       Name   Age   City
0    Pushpa  22.0    Hyd
1    bhavya  28.0  Delhi
3  sathvika  21.0  delhi
5      abhi  25.0    Hyd

In [6]:
#  FIling Missing Values

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])

df

       Name   Age   City
0    Pushpa  22.0    Hyd
1    bhavya  28.0  Delhi
2  varshini  25.2    hyd
3  sathvika  21.0  delhi
4    Pushpa  30.0  Delhi
5      abhi  25.0    Hyd

In [7]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, np.nan, 25, 30,20],
    "Salary": [20000, 25000, np.nan, 40000,20000],
    "City": ["Mumbai", "Delhi", "Pune", "Mumbai","Mumbai"]
})

df

    Age   Salary    City
0  20.0  20000.0  Mumbai
1   NaN  25000.0   Delhi
2  25.0      NaN    Pune
3  30.0  40000.0  Mumbai
4  20.0  20000.0  Mumbai

In [8]:
# Fill multiple columns with mean

df[["Age", "Salary"]] = df[["Age", "Salary"]].fillna(df[["Age", "Salary"]].mean())

df

     Age   Salary    City
0  20.00  20000.0  Mumbai
1  23.75  25000.0   Delhi
2  25.00  26250.0    Pune
3  30.00  40000.0  Mumbai
4  20.00  20000.0  Mumbai

In [9]:
# Convert multiple columns to integer

df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)

df.dtypes
df

   Age  Salary    City
0   20   20000  Mumbai
1   23   25000   Delhi
2   25   26250    Pune
3   30   40000  Mumbai
4   20   20000  Mumbai

In [10]:
# Increase values by 10%

df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)

df

    Age   Salary    City
0  22.0  22000.0  Mumbai
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  Mumbai
4  22.0  22000.0  Mumbai

In [11]:
df

    Age   Salary    City
0  22.0  22000.0  Mumbai
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  Mumbai
4  22.0  22000.0  Mumbai

In [13]:
# Replace specific values

df[["City"]] = df[["City"]].replace("Mumbai", "MUMBAI")
df

    Age   Salary    City
0  22.0  22000.0  MUMBAI
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  MUMBAI
4  22.0  22000.0  MUMBAI

In [14]:
df

    Age   Salary    City
0  22.0  22000.0  MUMBAI
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  MUMBAI
4  22.0  22000.0  MUMBAI

In [15]:
#Encoding
df_encoded=pd.get_dummies(df,columns=["City"])
df_encoded

    Age   Salary  City_Delhi  City_MUMBAI  City_Pune
0  22.0  22000.0       False         True      False
1  25.3  27500.0        True        False      False
2  27.5  28875.0       False        False       True
3  33.0  44000.0       False         True      False
4  22.0  22000.0       False         True      False

In [16]:
df_no_dup = df.drop_duplicates()
df_no_dup

    Age   Salary    City
0  22.0  22000.0  MUMBAI
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  MUMBAI

In [18]:
# Convert all city names to lowercase
df["City"] = df["City"].str.upper()
df2=df.dropna()
df2

    Age   Salary    City
0  22.0  22000.0  MUMBAI
1  25.3  27500.0   DELHI
2  27.5  28875.0    PUNE
3  33.0  44000.0  MUMBAI
4  22.0  22000.0  MUMBAI

In [19]:
df2.dropna()
df2["Age"] = df2["Age"].astype(int)
print(df2)
df2.drop_duplicates()

   Age   Salary    City
0   22  22000.0  MUMBAI
1   25  27500.0   DELHI
2   27  28875.0    PUNE
3   33  44000.0  MUMBAI
4   22  22000.0  MUMBAI

   Age   Salary    City
0   22  22000.0  MUMBAI
1   25  27500.0   DELHI
2   27  28875.0    PUNE
3   33  44000.0  MUMBAI

In [21]:
from google.colab import files

uploaded = files.upload()

# Check uploaded file name
file_name = list(uploaded.keys())[0]
print("Uploaded file:", file_name)

Saving rainfall.csv to rainfall.csv
Uploaded file: rainfall.csv

In [22]:
import pandas as pd

# Load the uploaded file
df = pd.read_csv(file_name)
df.head()

,DIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,ANDAMAN & NICOBAR ISLANDS,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,ANDAMAN & NICOBAR ISLANDS,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,ANDAMAN & NICOBAR ISLANDS,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,ANDAMAN & NICOBAR ISLANDS,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [23]:
df.head()
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DIVISION  4116 non-null   object
 1   YEAR      4116 non-null   int64
 2   JAN       4112 non-null   float64
 3   FEB       4113 non-null   float64
 4   MAR       4110 non-null   float64
 5   APR       4112 non-null   float64
 6   MAY       4113 non-null   float64
 7   JUN       4111 non-null   float64
 8   JUL       4109 non-null   float64
 9   AUG       4112 non-null   float64
 10  SEP       4110 non-null   float64
 11  OCT       4109 non-null   float64
 12  NOV       4105 non-null   float64
 13  DEC       4106 non-null   float64
 14  ANNUAL    4090 non-null   float64
 15  Jan-Feb   4110 non-null   float64
 16  Mar-May   4107 non-null   float64
 17  Jun-Sep   4106 non-null   float64
 18  Oct-Dec   4103 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 611.1+ KB

DIVISION     0
YEAR         0
JAN          4
FEB          3
MAR          6
APR          4
MAY          3
JUN          5
JUL          7
AUG          4
SEP          6
OCT          7
NOV         11
DEC         10
ANNUAL      26
Jan-Feb      6
Mar-May      9
Jun-Sep     10
Oct-Dec     13
dtype: int64

In [24]:
df["DIVISION"] = df["DIVISION"].astype(str).str.strip()
df["DIVISION"] = pd.to_datetime(df["DIVISION"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DIVISION  0 non-null      datetime64[ns]
 1   YEAR      4116 non-null   int64
 2   JAN       4112 non-null   float64
 3   FEB       4113 non-null   float64
 4   MAR       4110 non-null   float64
 5   APR       4112 non-null   float64
 6   MAY       4113 non-null   float64
 7   JUN       4111 non-null   float64
 8   JUL       4109 non-null   float64
 9   AUG       4112 non-null   float64
 10  SEP       4110 non-null   float64
 11  OCT       4109 non-null   float64
 12  NOV       4105 non-null   float64
 13  DEC       4106 non-null   float64
 14  ANNUAL    4090 non-null   float64
 15  Jan-Feb   4110 non-null   float64
 16  Mar-May   4107 non-null   float64
 17  Jun-Sep   4106 non-null   float64
 18  Oct-Dec   4103 non-null   float64
dtypes: datetime64[ns](1), float64(17), int64(1)
memory usage: 611.1 KB

/tmp/ipykernel_5636/3801233669.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["DIVISION"] = pd.to_datetime(df["DIVISION"], errors="coerce")

In [25]:
df["YEAR"] = df["YEAR"].astype(str).str.strip()
df["YEAR"] = pd.to_datetime(df["YEAR"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DIVISION  0 non-null      datetime64[ns]
 1   YEAR      4116 non-null   datetime64[ns]
 2   JAN       4112 non-null   float64
 3   FEB       4113 non-null   float64
 4   MAR       4110 non-null   float64
 5   APR       4112 non-null   float64
 6   MAY       4113 non-null   float64
 7   JUN       4111 non-null   float64
 8   JUL       4109 non-null   float64
 9   AUG       4112 non-null   float64
 10  SEP       4110 non-null   float64
 11  OCT       4109 non-null   float64
 12  NOV       4105 non-null   float64
 13  DEC       4106 non-null   float64
 14  ANNUAL    4090 non-null   float64
 15  Jan-Feb   4110 non-null   float64
 16  Mar-May   4107 non-null   float64
 17  Jun-Sep   4106 non-null   float64
 18  Oct-Dec   4103 non-null   float64
dtypes: datetime64[ns](2), float64(17)
memory usage: 611.1 KB

In [33]:
print(df.head())
print(df.columns)

                    DIVISION  YEAR   JAN    FEB   MAR    APR    MAY    JUN  \
0  ANDAMAN & NICOBAR ISLANDS  1901  49.2   87.1  29.2    2.3  528.8  517.5
1  ANDAMAN & NICOBAR ISLANDS  1902   0.0  159.8  12.2    0.0  446.1  537.1
2  ANDAMAN & NICOBAR ISLANDS  1903  12.7  144.0   0.0    1.0  235.1  479.9
3  ANDAMAN & NICOBAR ISLANDS  1904   9.4   14.7   0.0  202.4  304.5  495.1
4  ANDAMAN & NICOBAR ISLANDS  1905   1.3    0.0   3.3   26.9  279.5  628.7

     JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  \
0  365.1  481.1  332.6  388.5  558.2   33.6  3373.2    136.3    560.3
1  228.9  753.7  666.2  197.2  359.0  160.5  3520.7    159.8    458.3
2  728.4  326.7  339.0  181.2  284.4  225.0  2957.4    156.7    236.1
3  502.0  160.1  820.4  222.2  308.7   40.1  3079.6     24.1    506.9
4  368.7  330.5  297.0  260.7   25.4  344.7  2566.7      1.3    309.7

   Jun-Sep  Oct-Dec
0   1696.3    980.3
1   2185.9    716.7
2   1874.0    690.6
3   1977.6    571.0
4   1624.9    630.8
Index(['DIVISION', 'YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL',
       'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Jan-Feb', 'Mar-May',
       'Jun-Sep', 'Oct-Dec'],
      dtype='object')

In [34]:
import pandas as pd

# Numerical columns
num_cols = ["YEAR", "JAN", "FEB", "MAR", "APR", "MAY",
            "JUN", "JUL", "AUG", "SEP", "OCT", "NOV",
            "DEC", "ANNUAL", "Jan-Feb", "Mar-May",
            "Jun-Sep", "Oct-Dec"]

# Fill numerical missing values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Fill categorical missing values with mode
df["DIVISION"] = df["DIVISION"].fillna(df["DIVISION"].mode()[0])

# Check missing values
print(df.isnull().sum())

DIVISION    0
YEAR        0
JAN         0
FEB         0
MAR         0
APR         0
MAY         0
JUN         0
JUL         0
AUG         0
SEP         0
OCT         0
NOV         0
DEC         0
ANNUAL      0
Jan-Feb     0
Mar-May     0
Jun-Sep     0
Oct-Dec     0
dtype: int64

In [35]:
# Convert DIVISION names to lowercase
df["DIVISION"] = df["DIVISION"].astype(str).str.lower()

# Display unique divisions
print(df["DIVISION"].unique())
df

['andaman & nicobar islands' 'arunachal pradesh' 'assam & meghalaya'
 'naga mani mizo tripura' 'sub himalayan west bengal & sikkim'
 'gangetic west bengal' 'orissa' 'jharkhand' 'bihar' 'east uttar pradesh'
 'west uttar pradesh' 'uttarakhand' 'haryana delhi & chandigarh' 'punjab'
 'himachal pradesh' 'jammu & kashmir' 'west rajasthan' 'east rajasthan'
 'west madhya pradesh' 'east madhya pradesh' 'gujarat region'
 'saurashtra & kutch' 'konkan & goa' 'madhya maharashtra' 'matathwada'
 'vidarbha' 'chhattisgarh' 'coastal andhra pradesh' 'telangana'
 'rayalseema' 'tamil nadu' 'coastal karnataka' 'north interior karnataka'
 'south interior karnataka' 'kerala' 'lakshadweep']

,DIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,andaman & nicobar islands,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,andaman & nicobar islands,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,andaman & nicobar islands,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,andaman & nicobar islands,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,andaman & nicobar islands,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4111,lakshadweep,2011,5.1,2.8,3.1,85.9,107.2,153.6,350.2,254.0,255.2,117.4,184.3,14.9,1533.7,7.9,196.2,1013.0,316.6
4112,lakshadweep,2012,19.2,0.1,1.6,76.8,21.2,327.0,231.5,381.2,179.8,145.9,12.4,8.8,1405.5,19.3,99.6,1119.5,167.1
4113,lakshadweep,2013,26.2,34.4,37.5,5.3,88.3,426.2,296.4,154.4,180.0,72.8,78.1,26.7,1426.3,60.6,131.1,1057.0,177.6
4114,lakshadweep,2014,53.2,16.1,4.4,14.9,57.4,244.1,116.1,466.1,132.2,169.2,59.0,62.3,1395.0,69.3,76.7,958.5,290.5
4115,lakshadweep,2015,2.2,0.5,3.7,87.1,133.1,296.6,257.5,146.4,160.4,165.4,231.0,159.0,1642.9,2.7,223.9,860.9,555.4

In [36]:
df.to_csv("cleaned_rainfall.csv", index=False)

In [37]:
import pandas as pd
from google.colab import files

# Convert to Excel
df.to_excel("cleaned_rainfall.xlsx", index=False)

# Download
files.download("cleaned_rainfall.xlsx")

In [38]:
import pandas as pd
import numpy as np

data = {
    "name": ["Amit", "Sara", "John", "Amit", None],
    "age": [20, 21, np.nan, 20, 19],
    "gender": ["Male", "female", "Male", "Male", "FEMALE"],
    "marks": [85, 90, 105, 85, -5],
    "attendance": [90, 85, 80, 90, None],
    "city": ["Mumbai", "Delhi", "mumbai", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df

   name   age  gender  marks  attendance    city
0  Amit  20.0    Male     85        90.0  Mumbai
1  Sara  21.0  female     90        85.0   Delhi
2  John   NaN    Male    105        80.0  mumbai
3  Amit  20.0    Male     85        90.0  Mumbai
4  None  19.0  FEMALE     -5         NaN    Pune

In [39]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   age         4 non-null      float64
 2   gender      5 non-null      object
 3   marks       5 non-null      int64
 4   attendance  4 non-null      float64
 5   city        5 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 372.0+ bytes

             age       marks  attendance
count   4.000000    5.000000    4.000000
mean   20.000000   72.000000   86.250000
std     0.816497   43.817805    4.787136
min    19.000000   -5.000000   80.000000
25%    19.750000   85.000000   83.750000
50%    20.000000   85.000000   87.500000
75%    20.250000   90.000000   90.000000
max    21.000000  105.000000   90.000000

In [40]:
df["age"].fillna(df["age"].mean(), inplace=True)
df["attendance"].fillna(df["attendance"].mean(), inplace=True)
df["name"].fillna("Unknown", inplace=True)

df

/tmp/ipykernel_5636/1440735091.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)
/tmp/ipykernel_5636/1440735091.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["attendance"].fillna(df["attendance"].mean(), inplace=True)
/tmp/ipykernel_5636/1440735091.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["name"].fillna("Unknown", inplace=True)

      name   age  gender  marks  attendance    city
0     Amit  20.0    Male     85       90.00  Mumbai
1     Sara  21.0  female     90       85.00   Delhi
2     John  20.0    Male    105       80.00  mumbai
3     Amit  20.0    Male     85       90.00  Mumbai
4  Unknown  19.0  FEMALE     -5       86.25    Pune

In [41]:
df["gender"] = df["gender"].str.lower()
df["city"] = df["city"].str.lower()

df

      name   age  gender  marks  attendance    city
0     Amit  20.0    male     85       90.00  mumbai
1     Sara  21.0  female     90       85.00   delhi
2     John  20.0    male    105       80.00  mumbai
3     Amit  20.0    male     85       90.00  mumbai
4  Unknown  19.0  female     -5       86.25    pune

In [42]:
df = df[(df["marks"] >= 0) & (df["marks"] <= 100)]

df

   name   age  gender  marks  attendance    city
0  Amit  20.0    male     85        90.0  mumbai
1  Sara  21.0  female     90        85.0   delhi
3  Amit  20.0    male     85        90.0  mumbai

## 🔹 Basic Questions

1. Load a CSV file and display:
   - First 5 rows
   - Last 5 rows

2. Find:
   - Total number of rows & columns
   - Data types of each column

3. Identify missing values:
   - Which columns have missing values?
   - Count them

4. Fill missing values:
   - Numerical → mean
   - Categorical → mode

5. Remove duplicate rows

6. Convert a column:
   - "date" → datetime format

7. Rename columns:
   - Change column names to lowercase

8. Change data type:
   - Convert float → int (where applicable)

In [43]:
#TASK GIVEN BY NIKITHA MAM
import pandas as pd

df = pd.read_csv("rainfall.csv")
# First 5 rows
print(df.head())
# Last 5 rows
print(df.tail())

                    DIVISION  YEAR   JAN    FEB   MAR    APR    MAY    JUN  \
0  ANDAMAN & NICOBAR ISLANDS  1901  49.2   87.1  29.2    2.3  528.8  517.5
1  ANDAMAN & NICOBAR ISLANDS  1902   0.0  159.8  12.2    0.0  446.1  537.1
2  ANDAMAN & NICOBAR ISLANDS  1903  12.7  144.0   0.0    1.0  235.1  479.9
3  ANDAMAN & NICOBAR ISLANDS  1904   9.4   14.7   0.0  202.4  304.5  495.1
4  ANDAMAN & NICOBAR ISLANDS  1905   1.3    0.0   3.3   26.9  279.5  628.7

     JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  \
0  365.1  481.1  332.6  388.5  558.2   33.6  3373.2    136.3    560.3
1  228.9  753.7  666.2  197.2  359.0  160.5  3520.7    159.8    458.3
2  728.4  326.7  339.0  181.2  284.4  225.0  2957.4    156.7    236.1
3  502.0  160.1  820.4  222.2  308.7   40.1  3079.6     24.1    506.9
4  368.7  330.5  297.0  260.7   25.4  344.7  2566.7      1.3    309.7

   Jun-Sep  Oct-Dec
0   1696.3    980.3
1   2185.9    716.7
2   1874.0    690.6
3   1977.6    571.0
4   1624.9    630.8
         DIVISION  YEAR   JAN   FEB   MAR   APR    MAY    JUN    JUL    AUG  \
4111  LAKSHADWEEP  2011   5.1   2.8   3.1  85.9  107.2  153.6  350.2  254.0
4112  LAKSHADWEEP  2012  19.2   0.1   1.6  76.8   21.2  327.0  231.5  381.2
4113  LAKSHADWEEP  2013  26.2  34.4  37.5   5.3   88.3  426.2  296.4  154.4
4114  LAKSHADWEEP  2014  53.2  16.1   4.4  14.9   57.4  244.1  116.1  466.1
4115  LAKSHADWEEP  2015   2.2   0.5   3.7  87.1  133.1  296.6  257.5  146.4

        SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  Jun-Sep  Oct-Dec
4111  255.2  117.4  184.3   14.9  1533.7      7.9    196.2   1013.0    316.6
4112  179.8  145.9   12.4    8.8  1405.5     19.3     99.6   1119.5    167.1
4113  180.0   72.8   78.1   26.7  1426.3     60.6    131.1   1057.0    177.6
4114  132.2  169.2   59.0   62.3  1395.0     69.3     76.7    958.5    290.5
4115  160.4  165.4  231.0  159.0  1642.9      2.7    223.9    860.9    555.4

In [44]:
# Total rows and columns
print("Rows and Columns:", df.shape)
# Data types
print(df.dtypes)

Rows and Columns: (4116, 19)
DIVISION     object
YEAR          int64
JAN         float64
FEB         float64
MAR         float64
APR         float64
MAY         float64
JUN         float64
JUL         float64
AUG         float64
SEP         float64
OCT         float64
NOV         float64
DEC         float64
ANNUAL      float64
Jan-Feb     float64
Mar-May     float64
Jun-Sep     float64
Oct-Dec     float64
dtype: object

In [45]:
# Missing values in each column
print(df.isnull().sum())

DIVISION     0
YEAR         0
JAN          4
FEB          3
MAR          6
APR          4
MAY          3
JUN          5
JUL          7
AUG          4
SEP          6
OCT          7
NOV         11
DEC         10
ANNUAL      26
Jan-Feb      6
Mar-May      9
Jun-Sep     10
Oct-Dec     13
dtype: int64

In [46]:
# Numerical columns
num_cols = df.select_dtypes(include="number").columns

# Fill numerical missing values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Fill categorical column with mode
if not df["DIVISION"].mode().empty:
    df["DIVISION"] = df["DIVISION"].fillna(df["DIVISION"].mode().iloc[0])

print(df.isnull().sum())

DIVISION    0
YEAR        0
JAN         0
FEB         0
MAR         0
APR         0
MAY         0
JUN         0
JUL         0
AUG         0
SEP         0
OCT         0
NOV         0
DEC         0
ANNUAL      0
Jan-Feb     0
Mar-May     0
Jun-Sep     0
Oct-Dec     0
dtype: int64

In [47]:
df = df.drop_duplicates()

print(df.shape)

(4116, 19)

In [48]:
df["YEAR"] = pd.to_datetime(df["YEAR"])

print(df["YEAR"].head())

0   1970-01-01 00:00:00.000001901
1   1970-01-01 00:00:00.000001902
2   1970-01-01 00:00:00.000001903
3   1970-01-01 00:00:00.000001904
4   1970-01-01 00:00:00.000001905
Name: YEAR, dtype: datetime64[ns]

In [49]:
df.columns = df.columns.str.lower()

print(df.columns)

Index(['division', 'year', 'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul',
       'aug', 'sep', 'oct', 'nov', 'dec', 'annual', 'jan-feb', 'mar-may',
       'jun-sep', 'oct-dec'],
      dtype='object')

In [50]:
# Convert annual rainfall to integer
df["annual"] = df["annual"].astype(int)

print(df.dtypes)

division            object
year        datetime64[ns]
jan                float64
feb                float64
mar                float64
apr                float64
may                float64
jun                float64
jul                float64
aug                float64
sep                float64
oct                float64
nov                float64
dec                float64
annual               int64
jan-feb            float64
mar-may            float64
jun-sep            float64
oct-dec            float64
dtype: object

## 🔹 Intermediate Questions

1. Select multiple columns and:
   - Fill missing values together

2. Apply transformation:
   - Increase salary/marks by 10%

3. Fix inconsistent text:
   - "Mumbai", "mumbai", "MUMBAI" → one format

4. Create new column:
   - Example: "Pass/Fail" based on marks

5. Filter data:
   - Students with marks > 80
   - Rainfall > 10

6. Drop unnecessary columns:
   - Based on relevance

7. Apply One-Hot Encoding:
   - On categorical columns

8. Sort dataset:
   - Based on date or marks

In [52]:
import pandas as pd

df = pd.read_csv("rainfall.csv")

cols = ["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG",
        "SEP","OCT","NOV","DEC"]

df[cols] = df[cols].fillna(df[cols].mean())

print(df.isnull().sum())

DIVISION     0
YEAR         0
JAN          0
FEB          0
MAR          0
APR          0
MAY          0
JUN          0
JUL          0
AUG          0
SEP          0
OCT          0
NOV          0
DEC          0
ANNUAL      26
Jan-Feb      6
Mar-May      9
Jun-Sep     10
Oct-Dec     13
dtype: int64

In [53]:
df["ANNUAL"] = df["ANNUAL"] * 1.10

print(df["ANNUAL"].head())

0    3710.52
1    3872.77
2    3253.14
3    3387.56
4    2823.37
Name: ANNUAL, dtype: float64

In [54]:
df["DIVISION"] = df["DIVISION"].astype(str).str.title()

print(df["DIVISION"].unique())

['Andaman & Nicobar Islands' 'Arunachal Pradesh' 'Assam & Meghalaya'
 'Naga Mani Mizo Tripura' 'Sub Himalayan West Bengal & Sikkim'
 'Gangetic West Bengal' 'Orissa' 'Jharkhand' 'Bihar' 'East Uttar Pradesh'
 'West Uttar Pradesh' 'Uttarakhand' 'Haryana Delhi & Chandigarh' 'Punjab'
 'Himachal Pradesh' 'Jammu & Kashmir' 'West Rajasthan' 'East Rajasthan'
 'West Madhya Pradesh' 'East Madhya Pradesh' 'Gujarat Region'
 'Saurashtra & Kutch' 'Konkan & Goa' 'Madhya Maharashtra' 'Matathwada'
 'Vidarbha' 'Chhattisgarh' 'Coastal Andhra Pradesh' 'Telangana'
 'Rayalseema' 'Tamil Nadu' 'Coastal Karnataka' 'North Interior Karnataka'
 'South Interior Karnataka' 'Kerala' 'Lakshadweep']

In [56]:
df["Rainfall_Status"] = df["ANNUAL"].apply(
    lambda x: "High" if x > 2500 else "Low"
)
df.head()

,DIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec,Rainfall_Status
0,Andaman & Nicobar Islands,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3710.52,136.3,560.3,1696.3,980.3,High
1,Andaman & Nicobar Islands,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3872.77,159.8,458.3,2185.9,716.7,High
2,Andaman & Nicobar Islands,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,3253.14,156.7,236.1,1874.0,690.6,High
3,Andaman & Nicobar Islands,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3387.56,24.1,506.9,1977.6,571.0,High
4,Andaman & Nicobar Islands,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2823.37,1.3,309.7,1624.9,630.8,High

In [57]:
high_rain = df[df["ANNUAL"] > 3000]

print(high_rain)

                       DIVISION  YEAR    JAN    FEB    MAR    APR    MAY  \
0     Andaman & Nicobar Islands  1901   49.2   87.1   29.2    2.3  528.8
1     Andaman & Nicobar Islands  1902    0.0  159.8   12.2    0.0  446.1
2     Andaman & Nicobar Islands  1903   12.7  144.0    0.0    1.0  235.1
3     Andaman & Nicobar Islands  1904    9.4   14.7    0.0  202.4  304.5
6     Andaman & Nicobar Islands  1907  110.7    0.0  113.3   21.6  616.3
...                         ...   ...    ...    ...    ...    ...    ...
3995                     Kerala  2009    3.3    1.5   62.6   69.0  191.6
3996                     Kerala  2010   18.6    1.0   31.4  138.9  190.6
3997                     Kerala  2011   20.5   45.7   24.1  165.2  124.2
3999                     Kerala  2013    3.9   40.1   49.9   49.3  119.3
4000                     Kerala  2014    4.6   10.3   17.9   95.7  251.0

         JUN    JUL    AUG    SEP    OCT    NOV    DEC   ANNUAL  Jan-Feb  \
0      517.5  365.1  481.1  332.6  388.5  558.2   33.6  3710.52    136.3
1      537.1  228.9  753.7  666.2  197.2  359.0  160.5  3872.77    159.8
2      479.9  728.4  326.7  339.0  181.2  284.4  225.0  3253.14    156.7
3      495.1  502.0  160.1  820.4  222.2  308.7   40.1  3387.56     24.1
6      305.2  443.9  377.6  200.4  264.4  648.9  245.6  3682.69    110.7
...      ...    ...    ...    ...    ...    ...    ...      ...      ...
3995   438.2  924.9  269.3  326.5  205.2  274.4   44.2  3091.66      4.8
3996   667.5  629.0  356.0  275.6  441.4  335.1   46.8  3444.98     19.6
3997   788.5  536.8  492.7  391.2  227.2  169.7   49.5  3338.61     66.2
3999  1042.7  830.2  369.7  318.6  259.9  154.9   17.0  3580.94     43.9
4000   454.4  677.8  733.9  298.8  355.5   99.5   47.2  3351.04     14.9

      Mar-May  Jun-Sep  Oct-Dec Rainfall_Status
0       560.3   1696.3    980.3            High
1       458.3   2185.9    716.7            High
2       236.1   1874.0    690.6            High
3       506.9   1977.6    571.0            High
6       751.2   1327.1   1158.9            High
...       ...      ...      ...             ...
3995    323.1   1958.9    523.8            High
3996    360.9   1928.0    823.3            High
3997    313.5   2209.1    446.3            High
3999    218.5   2561.2    431.8            High
4000    364.5   2164.8    502.1            High

[519 rows x 20 columns]

In [58]:
july = df[df["JUL"] > 500]

print(july)

                       DIVISION  YEAR   JAN    FEB         MAR         APR  \
2     Andaman & Nicobar Islands  1903  12.7  144.0    0.000000    1.000000
3     Andaman & Nicobar Islands  1904   9.4   14.7    0.000000  202.400000
12    Andaman & Nicobar Islands  1914   0.0    0.0    0.000000   37.700000
21    Andaman & Nicobar Islands  1923  79.5    0.0   27.359197   91.300000
34    Andaman & Nicobar Islands  1936  16.5   15.3  116.500000   43.127432
...                         ...   ...   ...    ...         ...         ...
3997                     Kerala  2011  20.5   45.7   24.100000  165.200000
3999                     Kerala  2013   3.9   40.1   49.900000   49.300000
4000                     Kerala  2014   4.6   10.3   17.900000   95.700000
4051                Lakshadweep  1951  24.3   28.9   35.300000  129.900000
4053                Lakshadweep  1953  10.4   40.8    9.300000   35.000000

        MAY     JUN    JUL    AUG    SEP    OCT    NOV    DEC   ANNUAL  \
2     235.1   479.9  728.4  326.7  339.0  181.2  284.4  225.0  3253.14
3     304.5   495.1  502.0  160.1  820.4  222.2  308.7   40.1  3387.56
12    298.8   383.3  792.8  520.5  310.8  139.8  184.4  289.7  3253.58
21    293.5   808.4  636.9  182.2  560.5  131.9  197.4   70.6      NaN
34    194.3   498.3  664.8  562.9  383.8  174.9  199.2  212.2      NaN
...     ...     ...    ...    ...    ...    ...    ...    ...      ...
3997  124.2   788.5  536.8  492.7  391.2  227.2  169.7   49.5  3338.61
3999  119.3  1042.7  830.2  369.7  318.6  259.9  154.9   17.0  3580.94
4000  251.0   454.4  677.8  733.9  298.8  355.5   99.5   47.2  3351.04
4051  108.4   445.1  524.2   43.7  156.0   68.6  103.6   47.3  1886.83
4053   15.3   205.8  537.0   69.4  125.5  452.4   95.6    9.7  1766.82

      Jan-Feb  Mar-May  Jun-Sep  Oct-Dec Rainfall_Status
2       156.7    236.1   1874.0    690.6            High
3        24.1    506.9   1977.6    571.0            High
12        0.0    336.5   2007.4    613.9            High
21       79.5      NaN   2188.0    399.9             Low
34       31.8      NaN   2109.8    586.3             Low
...       ...      ...      ...      ...             ...
3997     66.2    313.5   2209.1    446.3            High
3999     43.9    218.5   2561.2    431.8            High
4000     14.9    364.5   2164.8    502.1            High
4051     53.2    273.6   1169.0    219.5             Low
4053     51.2     59.6    937.7    557.7             Low

[677 rows x 20 columns]

In [59]:
df = df.drop(columns=["Jan-Feb","Mar-May","Jun-Sep","Oct-Dec"])

print(df.columns)

Index(['DIVISION', 'YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL',
       'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Rainfall_Status'],
      dtype='object')

In [60]:
df = pd.get_dummies(df, columns=["DIVISION"])

print(df.head())

   YEAR   JAN    FEB   MAR    APR    MAY    JUN    JUL    AUG    SEP  ...  \
0  1901  49.2   87.1  29.2    2.3  528.8  517.5  365.1  481.1  332.6  ...
1  1902   0.0  159.8  12.2    0.0  446.1  537.1  228.9  753.7  666.2  ...
2  1903  12.7  144.0   0.0    1.0  235.1  479.9  728.4  326.7  339.0  ...
3  1904   9.4   14.7   0.0  202.4  304.5  495.1  502.0  160.1  820.4  ...
4  1905   1.3    0.0   3.3   26.9  279.5  628.7  368.7  330.5  297.0  ...

   DIVISION_Saurashtra & Kutch  DIVISION_South Interior Karnataka  \
0                        False                              False
1                        False                              False
2                        False                              False
3                        False                              False
4                        False                              False

   DIVISION_Sub Himalayan West Bengal & Sikkim  DIVISION_Tamil Nadu  \
0                                        False                False
1                                        False                False
2                                        False                False
3                                        False                False
4                                        False                False

  DIVISION_Telangana  DIVISION_Uttarakhand  DIVISION_Vidarbha  \
0              False                 False              False
1              False                 False              False
2              False                 False              False
3              False                 False              False
4              False                 False              False

   DIVISION_West Madhya Pradesh  DIVISION_West Rajasthan  \
0                         False                    False
1                         False                    False
2                         False                    False
3                         False                    False
4                         False                    False

   DIVISION_West Uttar Pradesh
0                        False
1                        False
2                        False
3                        False
4                        False

[5 rows x 51 columns]

In [61]:
df = df.sort_values(by="ANNUAL", ascending=False)

print(df.head())

      YEAR    JAN    FEB    MAR    APR     MAY     JUN     JUL    AUG    SEP  \
142   1948   35.6  119.5  136.1  441.1  1168.6   889.5  2362.8  603.3  350.4
132   1938  144.8  121.6  340.5  395.3   306.5  1511.3  1355.1  790.8  877.3
115   1921   78.9   54.3  180.3  358.0   598.0  1233.2  1433.0  885.9  603.4
3602  1961    0.0    0.0    0.9   47.7   635.0  1013.0  1884.9  936.3  702.8
112   1918   10.4   11.0  191.2  144.6   861.1  1609.9  1303.0  692.6  515.8

      ...  DIVISION_Saurashtra & Kutch  DIVISION_South Interior Karnataka  \
142   ...                        False                              False
132   ...                        False                              False
115   ...                        False                              False
3602  ...                        False                              False
112   ...                        False                              False

      DIVISION_Sub Himalayan West Bengal & Sikkim  DIVISION_Tamil Nadu  \
142                                         False                False
132                                         False                False
115                                         False                False
3602                                        False                False
112                                         False                False

     DIVISION_Telangana  DIVISION_Uttarakhand  DIVISION_Vidarbha  \
142               False                 False              False
132               False                 False              False
115               False                 False              False
3602              False                 False              False
112               False                 False              False

      DIVISION_West Madhya Pradesh  DIVISION_West Rajasthan  \
142                          False                    False
132                          False                    False
115                          False                    False
3602                         False                    False
112                          False                    False

      DIVISION_West Uttar Pradesh
142                         False
132                         False
115                         False
3602                        False
112                         False

[5 rows x 51 columns]